title: ColCh homepage
description: My Github pages website

url: http://colch.github.com/
baseurl: /

safe: true
auto: true

source: .
destination: ./_site

lsi: false
pygments: true

exclude:
  README.md
